### ISSUE TITLE
More dependencies

### ISSUE THREAD

**Issue by carlosedubarreto** [kwan3854/CEB_ECON#1]
when installing it asks for other dependencies
![image](https://github.com/kwan3854/CEB_ECON/assets/4061130/3b2a7928-aab8-4576-9144-16d5f4a06801)

but trying to execute it it gives an error
![image](https://github.com/kwan3854/CEB_ECON/assets/4061130/0ff86a35-f73e-4e89-a888-1219a28ef29a)

**Comment by kwan3854** [comment]
try
```
import subprocess
import sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "PyYAML"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "ruamel.yaml"])
```

<img width="558" alt="Screenshot" src="https://github.com/kwan3854/CEB_ECON/assets/30712687/0ce48a86-df1c-493c-a7af-728c64fe28d0">

**Comment by carlosedubarreto** [comment]
it worked, thanks 🙏
