### ISSUE TITLE
Install compiler

### ISSUE THREAD

**Issue by carlosedubarreto** [kwan3854/CEB_ECON#2]
Hello, I came a cross this option "Install compiler"
it would be the sme file that I made available as Zip for people to use?

if it is, I think you need to tell about where people could get it, I didnt find information on the github.

Or, there is a better option.
I found tht the best is to inform the user to install visual studio build tools and CUDA sdk.
Installing both is more reliable and it will be usefull for more addons and software the user might want to install. while this compiling strategy that I used at that time was not scalable and had a lot of "trash" in it.

But, back on the question, this install compiler would be the same one that is available on the original code?

**Comment by kwan3854** [comment]
I have updated the README page. Detailed installation guides and usage instructions have been added. As per your advice, I've also included information about the compiler. And you are correct, the install compiler used is identical to the one used in the original code.
